#!/usr/bin/env bash

CRIT_ID=9999
notified=false

while true; do
    battery=$(acpi -b | grep -P -o '[0-9]+(?=%)')
    status=$(acpi -b | grep -oE 'Charging|Discharging|Full')

    if [ "$status" = "Discharging" ]; then
        if [ "$battery" -le 70 ] && [ "$notified" = false ]; then
            dunstify -u critical -r $CRIT_ID \
            "󰂃 Critical Battery — ${battery}%" \
            "Charge immediately to prevent shutdown."
            notified=true
        fi
    else
        if [ "$notified" = true ]; then
            dunstify -r $CRIT_ID -t 1 ""
            notified=false
        fi
    fi

    sleep 10
done
