#!/usr/bin/env bash

install_time=$(stat -c %W /)
current_time=$(date +%s)

if [[ "$install_time" -le 0 ]]; then
  install_time=$(stat -c %Y /var/log/pacman.log)
fi

install_datetime=$(date -d "@$install_time" "+%Y-%m-%d %H:%M:%S")

age_seconds=$((current_time - install_time))

seconds=$((age_seconds % 60))
total_minutes=$((age_seconds / 60))
minutes=$((total_minutes % 60))
total_hours=$((total_minutes / 60))
hours=$((total_hours % 24))
total_days=$((total_hours / 24))
days=$((total_days % 30))
total_months=$((total_days / 30))
months=$((total_months % 12))
years=$((total_months / 12))

p() { [[ $1 -eq 1 ]] && echo "$1 $2" || echo "$1 ${2}s"; }

echo "System Install Date & Time: $install_datetime"
echo
echo "Time Since Install:"
printf "In Seconds: %s\n" "$(p "$age_seconds" second)"
printf "In Minutes: %s, %s\n" "$(p "$total_minutes" minute)" "$(p "$seconds" second)"
printf "In Hours:   %s, %s, %s\n" "$(p "$total_hours" hour)" "$(p "$minutes" minute)" "$(p "$seconds" second)"
printf "In Days:    %s, %s, %s, %s\n" "$(p "$total_days" day)" "$(p "$hours" hour)" "$(p "$minutes" minute)" "$(p "$seconds" second)"
printf "In Months:  %s, %s, %s, %s, %s\n" "$(p "$total_months" month)" "$(p "$days" day)" "$(p "$hours" hour)" "$(p "$minutes" minute)" "$(p "$seconds" second)"
printf "In Years:   %s, %s, %s, %s, %s, %s\n" "$(p "$years" year)" "$(p "$months" month)" "$(p "$days" day)" "$(p "$hours" hour)" "$(p "$minutes" minute)" "$(p "$seconds" second)"
