include colorscheme.conf
font_family JetBrains Mono Nerd Font
font_size 20.0
background_opacity 0.95
cursor_shape block
cursor_blink_interval 0
cursor_trail 0
confirm_os_window_close 0
remember_window_size no
initial_window_width 80c
initial_window_height 24c
enable_audio_bell no
