# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  border: rounded
  theme:
    activeBorderColor:
      - "#cba6f7" # Mauve accent
      - bold
    inactiveBorderColor:
      - "#585b70" # Surface2
    searchingActiveBorderColor:
      - "#f9e2af" # Yellow
    optionsTextColor:
      - "#cdd6f4" # Text
    selectedLineBgColor:
      - "#313244" # Surface0
    cherryPickedCommitBgColor:
      - "#45475a" # Surface1
    cherryPickedCommitFgColor:
      - "#cba6f7" # Mauve accent
    unstagedChangesColor:
      - "#f38ba8" # Red
    defaultFgColor:
      - "#cdd6f4" # Text
